/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.deliveryslotmanagement

import io.restassured.RestAssured
import io.restassured.builder.RequestSpecBuilder
import org.junit.Test
import spock.lang.Specification

import static io.restassured.RestAssured.given

class EasyRestTest extends Specification {
    def requestSpec = new RequestSpecBuilder().setBaseUri(System.getProperty("easyRestBaseUrl")).build()

    @Test
    void "test availableSlots"() {
        RestAssured.useRelaxedHTTPSValidation()

        given:
        def request = given(requestSpec)

        when:
        def response = request.get('/electronics-spa/users/anonymous/carts/testDeliverySlotCartGUID/getAvailableSlots')

        and:
        if (response.statusCode() == 404) {
            println "API is not available, skipping test."
            return
        }

        then:
        response.then().statusCode(200)

    }
}
