/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.delivery

import com.sap.cx.boosters.easy.delivery.easytype.model.DeliverySlotManagementModel
import com.sap.cx.boosters.easy.delivery.service.DeliverySlotService
import de.hybris.platform.core.model.order.CartModel
import de.hybris.platform.enumeration.EnumerationService
import de.hybris.platform.servicelayer.model.ModelService
import de.hybris.platform.servicelayer.search.FlexibleSearchService
import de.hybris.platform.servicelayer.search.SearchResult
import org.junit.Test
import spock.lang.Specification

class DeliverySlotServiceTest extends Specification {

    def flexibleSearchService = Mock FlexibleSearchService
    def modelService = Mock ModelService
    def enumerationService = Mock EnumerationService

    @Test
    def "Cart has already a booked slot associated"() {
        given:
        def cart = Mock CartModel
        def deliverySlotService = new DeliverySlotService()
        deliverySlotService.setFlexibleSearchService(flexibleSearchService)
        deliverySlotService.setEnumerationService(enumerationService)
        deliverySlotService.setModelService(modelService)
        flexibleSearchService.search(DeliverySlotService.QUERY_GET_SLOT_MANAGEMENT_BY_CART, _) >> searchResult

        when:
        def result = deliverySlotService.bookDelivery("slot", cart)

        then:
        result == null
    }

    def searchResult = Stub(SearchResult) {
        getResult() >> [Stub(DeliverySlotManagementModel)]
        getCount() >> 1
    }

}
