/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.delivery


import com.sap.cx.boosters.easy.delivery.service.HelloWorldService
import org.junit.Test
import spock.lang.Specification

class HelloWorldServiceTest extends Specification {

    @Test
    def "Test Hello World"() {
        given:
        def helloWorldService = new HelloWorldService()

        when:
        def result = helloWorldService.helloWorld()

        then:
        result == "Hello World!"
    }

}
