/*
* Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved.
* ----------------------------------------------------------------
* --- WARNING: THIS FILE IS GENERATED BY EASY GRADLE PLUGIN AND WILL BE
* --- OVERWRITTEN IF REGENERATED AGAIN USING easy-class-gen GRADLE TASK!
* --- Generated at Wed Nov 29 19:41:13 GMT 2023
* ----------------------------------------------------------------
*/

package com.sap.cx.boosters.easy.easytutorialstep6.models

import de.hybris.platform.core.model.order.CartModel
import com.sap.cx.boosters.easy.easytutorialstep6.models.DeliverySlotManagementModel
import de.hybris.bootstrap.annotations.Accessor
import de.hybris.platform.servicelayer.model.ItemModelContext

/**
* Generated model class for easy type Cart.
*/
class DeliverySlotManagementCartModel extends CartModel {

    /**<i>Generated model type code constant.</i>*/
    public static final String _TYPECODE = "Cart"

    /** <i>Generated constant</i> - Attribute key of <code>Cart.deliveryslotmanagement</code>. */
    public static final String DELIVERYSLOTMANAGEMENT = "deliveryslotmanagement"

    /**
    * <i>Generated constructor</i> - Default constructor for generic creation.
    */
    DeliverySlotManagementCartModel() {
        super()
    }

    /**
    * <i>Generated constructor</i> - Default constructor for creation with existing context
    * @param ctx the model context to be injected, must not be null
    */
    DeliverySlotManagementCartModel(final ItemModelContext ctx) {
        super(ctx)
    }


    /**
    * <i>Generated method</i> - Getter of the <code>Cart.deliveryslotmanagement</code> attribute.
    * @return the deliveryslotmanagement
    */
    @Accessor(qualifier = DELIVERYSLOTMANAGEMENT, type = Accessor.Type.GETTER)
    DeliverySlotManagementModel getDeliveryslotmanagement() {
        return getPersistenceContext().getDynamicValue(this, DELIVERYSLOTMANAGEMENT)
    }

}
