/*
* Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved.
* ----------------------------------------------------------------
* --- WARNING: THIS FILE IS GENERATED BY EASY GRADLE PLUGIN AND WILL BE
* --- OVERWRITTEN IF REGENERATED AGAIN USING easy-class-gen GRADLE TASK!
* --- Generated at Wed Nov 29 19:04:16 GMT 2023
* ----------------------------------------------------------------
*/

package com.sap.cx.boosters.easy.easytutorialstep4.enums

import de.hybris.platform.core.HybrisEnumValue

/**
* Generated easy enum DeliverySlotStatus declared in easy extension.
*/
enum DeliverySlotStatus implements HybrisEnumValue {

    /**
    * Generated easy enum value for DeliverySlotStatus.BOOKED declared in easy extension.
    */
    BOOKED("BOOKED"),

    /**
    * Generated easy enum value for DeliverySlotStatus.CONFIRMED declared in easy extension.
    */
    CONFIRMED("CONFIRMED")


    /**<i>Generated enum type code constant.</i>*/
    public static final String _TYPECODE = "DeliverySlotStatus"

    /**<i>Generated simple class name constant.</i>*/
    public static final String SIMPLE_CLASSNAME = "DeliverySlotStatus"

    /** The code of this enum.*/
    private final String code

    /**
    * Creates a new enum value for this enum type.
    *
    * @param code the enum value code
    */
    private DeliverySlotStatus(final String code) {
        this.code = code.intern()
    }

    /**
    * Gets the code of this enum value.
    *
    * @return code of value
    */
    @Override
    String getCode() {
        return this.code
    }

    /**
    * Gets the type this enum value belongs to.
    *
    * @return code of type
    */
    @Override
    String getType() {
        return SIMPLE_CLASSNAME
    }
}
