/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.easytutorialstep3

import com.sap.cx.boosters.easy.easytutorialstep3.service.DeliverySlotService
import com.sap.cx.boosters.easy.easytutorialstep3.service.impl.DefaultDeliverySlotService
import de.hybris.bootstrap.annotations.UnitTest
import de.hybris.platform.servicelayer.search.FlexibleSearchService
import org.junit.Before
import org.junit.Test
import org.mockito.InjectMocks
import org.mockito.Mock

import static org.junit.Assert.assertTrue
import static org.mockito.MockitoAnnotations.openMocks

@UnitTest
class DeliverySlotServiceTest {

    @InjectMocks
    private DeliverySlotService deliverySlotService

    @Mock
    private FlexibleSearchService flexibleSearchService

    @Before
    void setUp() throws Exception {
        deliverySlotService = new DefaultDeliverySlotService()
        openMocks(this).close()
    }

    @Test
    void testBookedDeliverySlot() {
        //TODO implement the test
        assertTrue(true)
    }
}
