/*
* Copyright (c) 2023 SAP SE or an SAP affiliate company. All rights reserved.
* ----------------------------------------------------------------
* --- WARNING: THIS FILE IS GENERATED BY EASY GRADLE PLUGIN AND WILL BE
* --- OVERWRITTEN IF REGENERATED AGAIN USING easy-class-gen GRADLE TASK!
* --- Generated at Wed Nov 29 18:15:17 GMT 2023
* ----------------------------------------------------------------
*/

package com.sap.cx.boosters.easy.easytutorialstep3.models

import de.hybris.platform.core.model.ItemModel
import com.sap.cx.boosters.easy.easytutorialstep3.models.VehicleModel
import de.hybris.platform.ordersplitting.model.WarehouseModel
import de.hybris.bootstrap.annotations.Accessor
import de.hybris.platform.servicelayer.model.ItemModelContext

/**
* Generated model class for easy type DeliverySlot.
*/
class DeliverySlotModel extends ItemModel {

    /**<i>Generated model type code constant.</i>*/
    public static final String _TYPECODE = "DeliverySlot"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.code</code>. */
    public static final String CODE = "code"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.starttime</code>. */
    public static final String STARTTIME = "starttime"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.vehicle</code>. */
    public static final String VEHICLE = "vehicle"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.available</code>. */
    public static final String AVAILABLE = "available"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.warehouse</code>. */
    public static final String WAREHOUSE = "warehouse"

    /** <i>Generated constant</i> - Attribute key of <code>DeliverySlot.endtime</code>. */
    public static final String ENDTIME = "endtime"

    /**
    * <i>Generated constructor</i> - Default constructor for generic creation.
    */
    DeliverySlotModel() {
        super()
    }

    /**
    * <i>Generated constructor</i> - Default constructor for creation with existing context
    * @param ctx the model context to be injected, must not be null
    */
    DeliverySlotModel(final ItemModelContext ctx) {
        super(ctx)
    }


    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.code</code> attribute.
    * @return the code
    */
    @Accessor(qualifier = CODE, type = Accessor.Type.GETTER)
    String getCode() {
        return getPersistenceContext().getPropertyValue(CODE)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.code</code> attribute.
    *
    * @param value the code
    */
    @Accessor(qualifier = CODE, type = Accessor.Type.SETTER)
    void setCode(final String value) {
        getPersistenceContext().setPropertyValue(CODE, value)
    }

    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.starttime</code> attribute.
    * @return the starttime
    */
    @Accessor(qualifier = STARTTIME, type = Accessor.Type.GETTER)
    Date getStarttime() {
        return getPersistenceContext().getPropertyValue(STARTTIME)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.starttime</code> attribute.
    *
    * @param value the starttime
    */
    @Accessor(qualifier = STARTTIME, type = Accessor.Type.SETTER)
    void setStarttime(final Date value) {
        getPersistenceContext().setPropertyValue(STARTTIME, value)
    }

    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.vehicle</code> attribute.
    * @return the vehicle
    */
    @Accessor(qualifier = VEHICLE, type = Accessor.Type.GETTER)
    VehicleModel getVehicle() {
        return getPersistenceContext().getPropertyValue(VEHICLE)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.vehicle</code> attribute.
    *
    * @param value the vehicle
    */
    @Accessor(qualifier = VEHICLE, type = Accessor.Type.SETTER)
    void setVehicle(final VehicleModel value) {
        getPersistenceContext().setPropertyValue(VEHICLE, value)
    }

    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.available</code> attribute.
    * @return the available
    */
    @Accessor(qualifier = AVAILABLE, type = Accessor.Type.GETTER)
    Integer getAvailable() {
        return getPersistenceContext().getPropertyValue(AVAILABLE)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.available</code> attribute.
    *
    * @param value the available
    */
    @Accessor(qualifier = AVAILABLE, type = Accessor.Type.SETTER)
    void setAvailable(final Integer value) {
        getPersistenceContext().setPropertyValue(AVAILABLE, value)
    }

    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.warehouse</code> attribute.
    * @return the warehouse
    */
    @Accessor(qualifier = WAREHOUSE, type = Accessor.Type.GETTER)
    WarehouseModel getWarehouse() {
        return getPersistenceContext().getPropertyValue(WAREHOUSE)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.warehouse</code> attribute.
    *
    * @param value the warehouse
    */
    @Accessor(qualifier = WAREHOUSE, type = Accessor.Type.SETTER)
    void setWarehouse(final WarehouseModel value) {
        getPersistenceContext().setPropertyValue(WAREHOUSE, value)
    }

    /**
    * <i>Generated method</i> - Getter of the <code>DeliverySlot.endtime</code> attribute.
    * @return the endtime
    */
    @Accessor(qualifier = ENDTIME, type = Accessor.Type.GETTER)
    Date getEndtime() {
        return getPersistenceContext().getPropertyValue(ENDTIME)
    }

    /**
    * <i>Generated method</i> - Setter of <code>DeliverySlot.endtime</code> attribute.
    *
    * @param value the endtime
    */
    @Accessor(qualifier = ENDTIME, type = Accessor.Type.SETTER)
    void setEndtime(final Date value) {
        getPersistenceContext().setPropertyValue(ENDTIME, value)
    }
}
