/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.delivery

import groovyx.net.http.HttpResponseDecorator
import spock.lang.Specification

import static org.apache.http.HttpStatus.SC_OK

class EasyRestTest extends Specification {
    def restClient = new RESTClientNew( "https://localhost:9002")

    def "test availableSlots"() {

        when:
        restClient.ignoreSSLIssues()
        HttpResponseDecorator response = restClient.get(path: '/easyrest/electronics-spa/users/anonymous/carts/testDeliverySlotCartGUID/getAvailableSlots')

        then:
        with(response) {
            status == SC_OK
        }


    }
}
