/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.sap.cx.boosters.easy.easytutorialstep5

import com.sap.cx.boosters.easy.easytutorialstep5.service.HelloWorldService
import com.sap.cx.boosters.easy.easytutorialstep5.service.impl.DefaultHelloWorldService
import de.hybris.bootstrap.annotations.UnitTest
import org.junit.Assert
import org.junit.Test

@UnitTest
class HelloWorldServiceTest {

    @Test
    void testHelloWorld() {
        HelloWorldService helloWorldService = new DefaultHelloWorldService()
        Assert.assertEquals("Hello World!", helloWorldService.helloWorld())
    }
}
